<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/2
 * Time: 22:36
 */

namespace app\admin\model;

use think\Model;
use think\model\concern\SoftDelete;
class Config extends Model
{
    //软删除
    use SoftDelete;
    protected $deleteTime = 'delete_time';
    protected $defaultSoftDelete = 0;

    //自动写入时间戳
    protected $autoWriteTimestamp =true;

    //字段类型转换
    protected $type =[
        'id'=>'integer',
    ];
    // 设置json类型字段
    protected $json = ['file_name',
                     'description',
                    ];
    //模型初始化
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub//继承父类初始化
        self::event('before_delete',function ($config){ //回调方法支持传入当前模型对象实例
            $config->is_delete = 1;
            $config->save();
        });
    }

//构造生成器

//数据表中类型字段，type返回值处理
    public function getTypeAttr($value)
    {
        $type = [
            0 => 'win',
            1 => 'linux',
        ];
        return $type[$value];
    }

    //数据表中状态字段，status返回值处理
    public function getStatusAttr($value)
    {
        $status = [
            0 => '已停用',
            1 => '已启用',
        ];
        return $status[$value];
    }
}